services:
  postgresql:
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432/tcp"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  server:
    build:
      args:
        - NODE_ENV=production
      context: .
      dockerfile: Dockerfile
    command: npm run start
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql
volumes:
  db:
